name: Build Windows Executable

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files for debugging
        run: dir  # Use 'ls' on Linux, 'dir' on Windows

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile tkinter_calculator_grid.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: tkinter_calculator_exe
          path: dist/tkinter_calculator_grid.exe
